import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';
import {createRequire} from 'node:module';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const require=createRequire(import.meta.url);
const {validateConfig}=require('../shared/core.js');
const store=process.argv[2] || 'san-lorenzo';
// La Malfa non viene generata né pubblicata finché non sarà autorizzata la migrazione.
if(store!=='san-lorenzo')throw new Error('Negozio non attivato: La Malfa resta invariata.');
const config=JSON.parse(await fs.readFile(path.join(root,'stores',store+'.json'),'utf8'));
validateConfig(config);
const target=path.join(root,'dist',store);
const sources=['shared','catalog'];
const hash=createHash('sha256');
for(const dir of sources)for(const name of (await fs.readdir(path.join(root,dir))).sort())hash.update(await fs.readFile(path.join(root,dir,name)));
hash.update(JSON.stringify(config));
const version=hash.digest('hex').slice(0,12);
await fs.mkdir(target,{recursive:true});
for(const dir of sources)for(const name of await fs.readdir(path.join(root,dir)))await fs.copyFile(path.join(root,dir,name),path.join(target,name));
await fs.writeFile(path.join(target,'config.js'),'window.PETSTORE_CONFIG = Object.freeze('+JSON.stringify(config,null,2)+');\n');
let html=await fs.readFile(path.join(target,'index.html'),'utf8');
html=html.replaceAll('San Lorenzo',config.storeName);
await fs.writeFile(path.join(target,'index.html'),html);
const manifest=JSON.parse(await fs.readFile(path.join(target,'manifest.json'),'utf8'));
manifest.name='Pet Store '+config.storeName;manifest.short_name=config.storeName;
await fs.writeFile(path.join(target,'manifest.json'),JSON.stringify(manifest,null,2)+'\n');
let sw=await fs.readFile(path.join(target,'sw.js'),'utf8');
sw=sw.replace("const CACHE='san-lorenzo-shell-v1';",`const PREFIX='petstore-${store}-shell-';\nconst CACHE=PREFIX+'${version}';`);
sw=sw.replace("key.startsWith('san-lorenzo-shell-')","key.startsWith(PREFIX)");
await fs.writeFile(path.join(target,'sw.js'),sw);
await fs.writeFile(path.join(target,'release.json'),JSON.stringify({storeId:store,version},null,2)+'\n');
await fs.writeFile(path.join(target,'.nojekyll'),'');
console.log(`Versione ${version}: ${target}`);
